Metrics/LineLength:
  Enabled: false
Style/GlobalVars:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
EndOfLine:
  Enabled: false
Style/SymbolProc:
  Enabled: false
